# User config
author: "Natalie Quek"
tagline: "Designer + illustrator"
description: "Hi, I'm Natalie! I'm a visual designer, marketer + urbanist."
keywords: "Art, Design, Illustration, Graphic Design"
email: "nsquek14@gmail.com"
linkedin: "https://www.linkedin.com/in/natalie-quek-2549bb133/"
instagram: "https://www.instagram.com/nsquek_design"
google: "https://drive.google.com/file/d/1T6sc4N664JB-ABOgI7SAHO_8sljxgT4M/view?usp=sharing"
github: "https://github.com/nsquek"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed